import './globals.css'

import { UserProvider } from '@/context/userContext'
import { ToastContainer } from "react-toastify";
import { ContactsProvider } from "@/context/contactsContext";
import "react-toastify/dist/ReactToastify.css"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="h-screen">
        <ToastContainer />
        <UserProvider>
          <ContactsProvider>
            {children}
          </ContactsProvider>
        </UserProvider>
      </body>
    </html>
  )
}
